version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: shoh
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - /path/to/local/data:/var/lib/postgresql/data
